### ISSUE TITLE
The plugin is incompatible with the current KeePass version... (2.51)

### ISSUE THREAD

**Issue by stefanteodoropol** [kee-org/keepassrpc#126]
Hi all

I've encoutered this error when upgrading to the latest version of KeePass v2.51.

I'm using the portable version of KeePass. Up to this latest upgrade I've never had this issue.

I've been using keepassrpc v1.14.0 [Latest].

This is the error message in detail:

[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
C:\Users\Stefan\OneDrive\Apps\KeyPass\Plugins\KeePassRPC.plgx

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
ResX file Type System.Drawing.Point, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in the data at line 120, position 4 cannot be located. Line 122, position 5. cannot be parsed.
System.Windows.Forms
   at System.Resources.ResXResourceReader.ParseXml(XmlTextReader reader)
   at System.Resources.ResXResourceReader.EnsureResData()
   at System.Resources.ResXResourceReader.GetEnumerator()
   at KeePass.Plugins.PlgxPlugin.CompileEmbeddedRes(PlgxPluginInfo plgx)
   at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
Void ParseXml(System.Xml.XmlTextReader)

Inner:
Type System.Drawing.Point, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in the data at line 120, position 4 cannot be located. Line 122, position 5.

[^] Details  [OK]

**Comment by stefanteodoropol** [comment]
Okay I feel silly.
Using a clean folder with the latest KeePass version and the plugin works.
I probably had some bad files left over in the folder from the previous version 2.50. 
I just dragged and dropped the contents of the new zip on top of the existing folder.
Deleting everything and using only the files from the new zip and the latest plugin worked fine.
Closing this....
