### ISSUE TITLE
interop with KeePassQuickUnlock

### ISSUE THREAD

**Issue by r2evans** [kee-org/keepassrpc#29]
I'm not sure where the problem lies. I've been using KP-2.38 with KPRPC-1.7.2 for a while with no issues. When I installed [KPQU](https://github.com/JanisEst/KeePassQuickUnlock), the next time I start KP, I get

>   ERROR! Please click on this box, press CTRL-C on your keyboard and paste into a new post on the KeeFox forum (http://keefox.org/help/forum). Doing this will help other people to use KeeFox without any unexpected error messages like this. Please briefly describe what you were doing when the problem occurred, which version of KeeFox, KeePass and Firefox you use and what other security software you run on your machine. Thanks! Technical detail follows: System.NullReferenceException: Object reference not set to an instance of an object.
>
>    at KeePassRPC.KeePassRPCClientConnection.Encrypt(String plaintext)
>
>    at KeePassRPC.KeePassRPCClientConnection.Signal(Signal signal, String methodName)

I click through it, and all seems fine: both KPRPC and KPQU work fine.

It seems intermittent, but the only common element to every time it fails is that KPQU and KPRPC are both active, with QU being compiled. (I've gone through multiple repeats of the combinations of one, the other, and both, purging the two `Plugins` files and `PluginCache` dirs each time.)

This is a cross-post issue with https://github.com/JanisEst/KeePassQuickUnlock/issues/28

Versions:
- win10
- Keepass-2.38
- KeeAgent-0.9.1.0
- KeePassQRCodeView-1.0.3.2
- KeePassQuickUnlock-2.4.0.0
- KeePassRPC-1.7.2.0
- KeeTrayTOTP-0.9.1

**Comment by r2evans** [comment]
It was [pointed out to me](https://github.com/JanisEst/KeePassQuickUnlock/issues/28#issuecomment-383278452) that I might need to read the release notes more closely ...
